- hosts: all
  tasks:
    - name: Copy result into result dir
      shell: |
        set -ex
        cp -rf ~/gpAdminLogs "{{ ansible_user_dir }}/workspace/test_results/"
        diff_file="/home/zuul/gpdb/src/test/regress/regression.diffs"
        test_summary="/home/zuul/gpdb/src/test/regress/regression.out"
        if [ -e "$diff_file" ]; then
          cp $diff_file "{{ ansible_user_dir }}/workspace/test_results/"
        fi
        if [ -e "$test_summary" ]; then
          cp $test_summary "{{ ansible_user_dir }}/workspace/test_results/"
        fi
      args:
        executable: /bin/bash
